### ISSUE TITLE
Command-Vorschläge bei falscher Schreibweise 

### ISSUE THREAD

**Issue by JKamsker** [coderdojo-linz/DiscordBot-DotNet#29]
Wenn der Benutzer das Kommando nicht kennt, welches er eben bekommen hat, soll der Bot Vorschläge machen, was der Benutzer gemeint haben könnte.

Das Ergebnis würde dann beispielsweise so aussehen:
![](https://i.imgur.com/rYoEVXS.png)

Für solch eine Funktionalität könnte man im [CommandHandlingService.cs#215](https://github.com/coderdojo-linz/DiscordBot-DotNet/blob/a57f8912861ec418ae40976114bff82cb02cf12a/DiscordBot/Services/Base/CommandHandlingService.cs#L215) ansetzen.

Um an die User-Nachricht zu kommen, könnt ihr `context?.Message?.Content` verwenden.

Zum vergleichen der strings könnte man den [Levenstein algorithmus](https://en.wikipedia.org/wiki/Levenshtein_distance) verwenden (Natürlich kannst du dir auch etwas eigenes einfallen lassen :) )

**Comment by blaumeise20** [comment]
Already done 😀
