### ISSUE TITLE
Themenliste für den Workshop

### ISSUE THREAD

**Issue by JKamsker** [coderdojo-linz/DiscordBot-DotNet#40]
Am 19.06 werden wir wieder gemeinsam an unserem Bot weiterarbeiten.

Für euch habe ich 2 Themen ausgearbeitet:
- Ein Minecraft "Dungeon", welches man nur lösen kann, indem man ein Modul in seinen Discord bot dazu baut.
> Vorraussetzung: Einen eigenen Minecraft account
> Vote mit ❤️ 
- Eine Funktion, welche vorschläge liefert, wenn der User ein falsches Kommando eingegeben hat
> ![image](https://user-images.githubusercontent.com/11245306/84749029-ba710100-afb9-11ea-9889-40176c51b97c.png)
 > Vote mit 🚀 

Falls du Ideen für andere Themen hast, kannst du mir sie im Kommentarfeld mitteilen.

**Comment by blaumeise20** [comment]
Why is this still open?
