### ISSUE TITLE
[Feature] Datenbankanbindung implementieren

### ISSUE THREAD

**Issue by JKamsker** [coderdojo-linz/DiscordBot-DotNet#41]
Irgendwann braucht der Bot eine Datenbank um dynamischer arbeiten zu können.

Wir können auch einen Workshop dazu machen, das wird dann aber ein längerer Vorgang.

**Comment by blaumeise20** [comment]
Sehr gerne! Macht garnichts, dass es länger dauert ;-)

**Comment by JKamsker** [comment]
> Sehr gerne! Macht garnichts, dass es länger dauert ;-)
Naja, das bedeutet aber auch , dass wir am ende des Workshops womöglich keine Sichtbaren neuen Features haben, da das nur die Grundlage für andere tolle Features wäre.

**Comment by blaumeise20** [comment]
Kein Problem :-)

**Comment by SIMULATAN** [comment]
Also keine sichtbaren Features: jaaa schon aber es öffnet uns die Welt 😂 
Würde meeega helfen für die zukünftigen Module, mach ich gerne mit 👍

**Comment by JKamsker** [comment]
Done
